#!/usr/bin/env bash

# mv ~/Steam/steamapps/workshop/content/107410/<MOD_ID> ~/steamcmd/arma3/@<ModName>


steam_args=$(awk -F, '{print $1}' mods.txt | xargs -l echo +workshop_download_item 107410)
echo $steam_args
steamcmd +login cabewz $steam_args +quit
#workshop_download_item 107410 450814997
#awk -F, '{print $1}' missions.txt | xargs -I @ cp -r "$HOME/.steam/steam/steamapps/workshop/content/107410/@/"  mpmissions

# Move missions with rename
while IFS="" read -r line || [ -n "$p" ]
do
  printf '%s\n' "$line"
  id=$(echo $line | awk -F, '{print $1}')
  mod_name="@$(echo $line | awk -F, '{print $2}')"
  if [ ! -d ~steam/arma3/$mod_name ]; then
      cp -r "$HOME/.steam/steam/steamapps/workshop/content/107410/$id" ~steam/arma3/$mod_name
      chmod 777 ~steam/arma3/$mod_name
  fi

done < mods.txt


