#!/usr/bin/env bash

chmod 777 server.cfg
ln -S $PWD/server.cfg ~steam/arma3
sudo su steam
cd ~steam/arma3
./arma3server -name=server -config=server.cfg \
-mod=@RHSUSAF \
-mod=@RHSRF \
-mod=@RHSGREF \
-mod=@RHSSAF \
-mod=@RHSPKL \
-mod=@ProjectOpfor \

exit
#mods 
-mod=@CBA
-mod=@CUPTerrainsCore
-mod=@CUPTerrainsMaps
-mod=@CUPWeapons
-mod=@CUPUnits
-mod=@CupVehicles
-mod=@ACE
-mod=@ALIVE

