#!/usr/bin/env bash

# chmod 777 server.cfg
trash ~steam/arma3/server.cfg
cp $PWD/server.cfg ~steam/arma3
cd ~steam/arma3
sudo -u steam ./arma3server -name=server -config=server.cfg \
-mod=@inidbi2 \
-mod=@rhsusaf \
-mod=@rhsrf \
-mod=@rhsgref \
-mod=@rhssaf \
-mod=@rhspkl \
-mod=@projectopfor \

exit
#mods 
-mod=@CBA
-mod=@CUPTerrainsCore
-mod=@CUPTerrainsMaps
-mod=@CUPWeapons
-mod=@CUPUnits
-mod=@CupVehicles
-mod=@ACE
-mod=@ALIVE

